### ISSUE TITLE
Results: this is normal?

### ISSUE THREAD

**Issue by elmre** [RomanEmelyanov/Meltdown#1]
![default](https://user-images.githubusercontent.com/3106214/34574374-42f4fc4a-f188-11e7-8bb2-3ef103b2c2d0.png)

What conclusions can be drawn?

**Comment by RomanEmelyanov** [comment]
No, bug still inside system.
You need to install update https://support.microsoft.com/en-us/help/4056892/windows-10-update-kb4056892

**Comment by RomanEmelyanov** [comment]
See also https://support.microsoft.com/en-us/help/4073119/windows-client-guidance-for-it-pros-to-protect-against-speculative-exe
